// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfPandaStack.Models;
using AppContext = OfPandaStack.Models.AppContext;

namespace OfPandaStack.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20201204185241_PandasDb")]
    partial class PandasDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("OfPandaStack.Models.Pregunta", b =>
                {
                    b.Property<int>("IdPregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Carrera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumResp")
                        .HasColumnType("int");

                    b.Property<string>("Nusuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Resuelto")
                        .HasColumnType("int");

                    b.Property<string>("Tema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tpregunta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioNusuario")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdPregunta");

                    b.HasIndex("UsuarioNusuario");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("OfPandaStack.Models.Usuario", b =>
                {
                    b.Property<string>("Nusuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasennia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nusuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("OfPandaStack.Models.Pregunta", b =>
                {
                    b.HasOne("OfPandaStack.Models.Usuario", "Usuario")
                        .WithMany("Preguntas")
                        .HasForeignKey("UsuarioNusuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OfPandaStack.Models.Usuario", b =>
                {
                    b.Navigation("Preguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
